### PR TITLE
0.0.6

### PR DESCRIPTION
**Pull request by danmunn**
Updated for redmine 2.0 (would suggest minor testing before pulling as there are no test cases for this plugin)

### CODE REVIEW

**Comment by cforce** [comment]
Tx for contributing.
Let the community test and wait me some time for bugs and fixing. I will then pull it later.

First tester: https://github.com/cforce/projects_tree_view/issues/5

**Comment by jwalkerbg** [comment]
I think it would be useful to allow plugin configuration.

Par example Versions column may be hidden and then the project view would be more compact when collapsed.

Also, when subprojects are expanded, their versions are listed in twice or more times because they are listed in the parents too. Is it useful or redundant?

**Comment by danmunn** [comment]
Thanks for the feedback, I was only updating the plugin to work with redmine 2.0, additional functionality requests should be raised a separate issue.

**Comment by cforce** [comment]
Merged in new testing branch

https://github.com/cforce/projects_tree_view/tree/redmine2.x

**Comment by cforce** [comment]
https://github.com/cforce/projects_tree_view/tree/redmine2.x

**Pull request closed without merging**
